### PR TITLE
Unify icons with map

### PR DESCRIPTION
**Pull request by petraduriancikova**
Icons that correspond to the MapTiler Map Icon set unified in design or added if they were missing.

GO-650

## Objective
Have the icons in geocoding search the same as in MapTiler maps.

## Description
Icons that correspond to the MapTiler Map Icon set unified in design or added if they were missing.

### Acceptance
Visual check.

### CODE REVIEW

**Review by jachym — APPROVED** [review]
ok

**Review by zdila — APPROVED** [review]
many icons won't be currently used

**Comment by petraduriancikova** [comment]
@zdila Yes, that's expected. I added them so we have all icons from maps available in case we would like to use them in future. If that's ok with you and doesn't take up too much space?

**Comment by zdila** [comment]
@petraduriancikova it is ok for me

**Pull request merged**
